In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\prana\Downloads\climate_change.csv")
df

Year  Month    MEI     CO2      CH4      N2O   CFC-11   CFC-12  \
0    1983      5  2.556  345.96  1638.59  303.677  191.324  350.113   
1    1983      6  2.167  345.52  1633.71  303.746  192.057  351.848   
2    1983      7  1.741  344.15  1633.22  303.795  192.818  353.725   
3    1983      8  1.130  342.25  1631.35  303.839  193.602  355.633   
4    1983      9  0.428  340.17  1648.40  303.901  194.392  357.465   
..    ...    ...    ...     ...      ...      ...      ...      ...   
303  2008      8 -0.266  384.15  1779.88  321.405  244.200  535.072   
304  2008      9 -0.643  383.09  1795.08  321.529  244.083  535.048   
305  2008     10 -0.780  382.99  1814.18  321.796  244.080  534.927   
306  2008     11 -0.621  384.13  1812.37  322.013  244.225  534.906   
307  2008     12 -0.666  385.56  1812.88  322.182  244.204  535.005   

           TSI  Aerosols   Temp  
0    1366.1024    0.0863  0.109  
1    1366.1208    0.0794  0.118  
2    1366.2850    0.0731  0.137  
3    1366.4202    0.0673  0.176  
4    1366.2335    0.0619  0.149  
..         ...       ...    ...  
303  1365.6570    0.0036  0.407  
304  1365.6647    0.0043  0.378  
305  1365.6759    0.0046  0.440  
306  1365.7065    0.0048  0.394  
307  1365.6926    0.0046  0.330  

[308 rows x 11 columns]

In [4]:
df.head()

Year  Month    MEI     CO2      CH4      N2O   CFC-11   CFC-12        TSI  \
0  1983      5  2.556  345.96  1638.59  303.677  191.324  350.113  1366.1024   
1  1983      6  2.167  345.52  1633.71  303.746  192.057  351.848  1366.1208   
2  1983      7  1.741  344.15  1633.22  303.795  192.818  353.725  1366.2850   
3  1983      8  1.130  342.25  1631.35  303.839  193.602  355.633  1366.4202   
4  1983      9  0.428  340.17  1648.40  303.901  194.392  357.465  1366.2335   

   Aerosols   Temp  
0    0.0863  0.109  
1    0.0794  0.118  
2    0.0731  0.137  
3    0.0673  0.176  
4    0.0619  0.149

In [6]:
df.tail(10)

Year  Month    MEI     CO2      CH4      N2O   CFC-11   CFC-12  \
298  2008      3 -1.635  385.97  1792.84  321.295  245.430  535.979   
299  2008      4 -0.942  387.16  1792.57  321.354  245.086  535.648   
300  2008      5 -0.355  388.50  1796.43  321.420  244.914  535.399   
301  2008      6  0.128  387.88  1791.80  321.447  244.676  535.128   
302  2008      7  0.003  386.42  1782.93  321.372  244.434  535.026   
303  2008      8 -0.266  384.15  1779.88  321.405  244.200  535.072   
304  2008      9 -0.643  383.09  1795.08  321.529  244.083  535.048   
305  2008     10 -0.780  382.99  1814.18  321.796  244.080  534.927   
306  2008     11 -0.621  384.13  1812.37  322.013  244.225  534.906   
307  2008     12 -0.666  385.56  1812.88  322.182  244.204  535.005   

           TSI  Aerosols   Temp  
298  1365.6726    0.0034  0.447  
299  1365.7146    0.0033  0.278  
300  1365.7175    0.0031  0.283  
301  1365.6730    0.0031  0.315  
302  1365.6720    0.0033  0.406  
303  1365.6570    0.0036  0.407  
304  1365.6647    0.0043  0.378  
305  1365.6759    0.0046  0.440  
306  1365.7065    0.0048  0.394  
307  1365.6926    0.0046  0.330

In [12]:
import pandas as pd

# Correct file path using a raw string
file_path = r"C:\Users\prana\OneDrive\Desktop\abc.xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df)


Sheet1 Content:
     Year  Month    MEI     CO2      CH4      N2O   CFC-11   CFC-12  \
0    1983      5  2.556  345.96  1638.59  303.677  191.324  350.113   
1    1983      6  2.167  345.52  1633.71  303.746  192.057  351.848   
2    1983      7  1.741  344.15  1633.22  303.795  192.818  353.725   
3    1983      8  1.130  342.25  1631.35  303.839  193.602  355.633   
4    1983      9  0.428  340.17  1648.40  303.901  194.392  357.465   
..    ...    ...    ...     ...      ...      ...      ...      ...   
303  2008      8 -0.266  384.15  1779.88  321.405  244.200  535.072   
304  2008      9 -0.643  383.09  1795.08  321.529  244.083  535.048   
305  2008     10 -0.780  382.99  1814.18  321.796  244.080  534.927   
306  2008     11 -0.621  384.13  1812.37  322.013  244.225  534.906   
307  2008     12 -0.666  385.56  1812.88  322.182  244.204  535.005   

           TSI  Aerosols   Temp  
0    1366.1024    0.0863  0.109  
1    1366.1208    0.0794  0.118  
2    1366.2850    0.0731  0.1

In [13]:
import numpy as np


In [14]:
a=np.ones(3)

In [15]:
a

array([1., 1., 1.])

In [16]:
type(a[0])

numpy.float64

In [17]:
z=np.zeros(10)

In [18]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
z.shape

(10,)

In [21]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
z=np.empty(3)
z

array([1., 1., 1.])

In [27]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])